[package]
name = "lawl"
version = "0.1.0"
edition = "2024"

[features]

[dependencies]
erased-serde = "0.4.9"
lol_html = "2.7.0"
mlua = { version = "0.11.5", features = ["lua54", "vendored", "serde"] }
